#!/usr/bin/env python3

import argparse
from collections import namedtuple
import http
import http.server
import prometheus_client
import re
import requests
import soco
import xml.etree.ElementTree as ElementTree

from prometheus_client.core import REGISTRY, GaugeMetricFamily


def main():
    parser = argparse.ArgumentParser(
        description="Prometheus exporter for Sonos networks")
    parser.add_argument("--address", default="localhost:1915",
                        help="Network address for this server")

    args = parser.parse_args()
    host, port = args.address.split(":", 1)

    REGISTRY.register(Collector())

    server = http.server.HTTPServer((host, int(port)), prometheus_client.MetricsHandler)
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        server.socket.close()


class Collector(object):

    def collect(self):
        rx_bytes = GaugeMetricFamily("sonos_rx_bytes", "Received bytes",
            labels=["player", "device"])
        tx_bytes = GaugeMetricFamily("sonos_tx_bytes", "Transmitted bytes",
            labels=["player", "device"])
        rx_packets = GaugeMetricFamily("sonos_rx_packets", "Received packets",
            labels=["player", "device"])
        tx_packets = GaugeMetricFamily("sonos_tx_packets", "Transmitted packets",
            labels=["player", "device"])
        uptime = GaugeMetricFamily("sonos_uptime_seconds", "System Uptime Seconds",
            labels=["player"])
        loadAvg1 = GaugeMetricFamily("sonos_load1", "1m load average",
            labels=["player"])
        loadAvg5 = GaugeMetricFamily("sonos_load5", "5m load average",
            labels=["player"])
        loadAvg15 = GaugeMetricFamily("sonos_load15", "15m load average",
            labels=["player"])

        zones = soco.discover()
        if zones is None:
            return
        for zone in zones:
            interfaceUrl = "http://%s:1400/status/ifconfig" % zone.ip_address
            body = requests.get(interfaceUrl).text
            ifconfig = get_ifconfig(body)

            for iface in parse_ifconfig(ifconfig):
                device = iface.name

                rx_bytes.add_metric([zone.player_name, device], value=float(iface.rxbytes))
                tx_bytes.add_metric([zone.player_name, device], value=float(iface.txbytes))
                rx_packets.add_metric([zone.player_name, device], value=float(iface.rxpkts))
                tx_packets.add_metric([zone.player_name, device], value=float(iface.txpkts))

            loadUrl = "http://%s:1400/status/uptime" % zone.ip_address
            body = requests.get(loadUrl).text
            load = get_load(body).replace(',', '').split()

            loadAvg1.add_metric([zone.player_name], value=float(load[-3]))
            loadAvg5.add_metric([zone.player_name], value=float(load[-2]))
            loadAvg15.add_metric([zone.player_name], value=float(load[-1]))

            zpUrl = "http://%s:1400/status/zp" % zone.ip_address
            body = requests.get(zpUrl).text
            ut = get_uptime(body)

            uptime.add_metric([zone.player_name], value=int(ut['UptimeSeconds']))

        yield rx_bytes
        yield tx_bytes
        yield rx_packets
        yield tx_packets
        yield loadAvg1
        yield loadAvg5
        yield loadAvg15
        yield uptime

def get_uptime(body):
    tree = ElementTree.fromstring(body)
    return dict((x.tag, x.text) for x in tree[0])

def get_load(body):
    tree = ElementTree.fromstring(body)
    return tree.find("Command[@cmdline='/usr/bin/uptime']").text.rstrip()

def get_ifconfig(body):
    tree = ElementTree.fromstring(body)
    return tree.find("Command[@cmdline='/sbin/ifconfig']").text


def parse_ifconfig(text):
    ifaces = []

    blocks = text.strip().split("\n\n")
    for block in blocks:
        ifaces.append(parse_interface(block))

    return ifaces

Iface = namedtuple("Iface", "name rxbytes txbytes rxpkts txpkts")

def parse_interface(block):
    # This is not exactly general purpose, but I'm figuring the upstream
    # release cycle means the format won't change often.
    #
    # My devices are currently giving out blank line separated blocks
    # like this:
    #
    # br0       Link encap:Ethernet  HWaddr B8:E9:37:52:6F:58
    #           inet addr:192.168.78.5  Bcast:192.168.78.255  Mask:255.255.255.0
    #           UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
    #           RX packets:1024606 errors:0 dropped:0 overruns:0 frame:0
    #           TX packets:522396 errors:0 dropped:0 overruns:0 carrier:0
    #           collisions:0 txqueuelen:0
    #           RX bytes:574772233 (548.1 MiB)  TX bytes:230409343 (219.7 MiB)

    name = re.search(r"^([^ ]+)", block).group(1)
    rxbytes = txbytes = rxpkts = txpkts = None

    m = re.search(r"RX bytes:(\d+)", block, re.I)
    if m:
        rxbytes = int(m.group(1))

    m = re.search(r"TX bytes:(\d+)", block, re.I)
    if m:
        txbytes = int(m.group(1))

    m = re.search(r"RX packets:(\d+)", block, re.I)
    if m:
        rxpkts = int(m.group(1))

    m = re.search(r"TX packets:(\d+)", block, re.I)
    if m:
        txpkts = int(m.group(1))

    return Iface(name=name, rxbytes=rxbytes, txbytes=txbytes, rxpkts=rxpkts, txpkts=txpkts)


if __name__ == "__main__":
    main()
